Initial live demo script.
itsallcode/openfasttrace-demo pull request #1
Opened 2018-05-20 10:15 UTC by redcatbear

:x: not ready for integration yet. Please wait.

2018-05-22 15:51 UTC, kaklakariada requested changes

2018-05-22 15:51 UTC, kaklakariada commented on oft-live-demo-medium.md
> +sudo apt install openjdk-8-jre vim libxml2-utils
Also install dependencies listed above, e.g. maven or jdk

2018-05-22 15:51 UTC, kaklakariada commented on oft-live-demo-medium.md
> +Set the necessary environment variables first. They are also needed in case you return later to a already set-up demonstration.
*an* already ...

2018-05-22 15:51 UTC, kaklakariada commented on oft-live-demo-medium.md
> +demodir="$HOME/tmp/$project-demo-medium"
Why do you use the suffix -demo-medium?

2018-05-22 15:51 UTC, kaklakariada commented on oft-live-demo-medium.md
> +* Java 8 JRE (or JDK)
JDK is required for building oft.

2018-05-22 15:51 UTC, kaklakariada commented on oft-live-demo-medium.md
> +The following command produces a list of all requirement ID from OFT's feature list.
requirement ID -> requirement IDs

2018-05-22 15:51 UTC, kaklakariada commented on oft-live-demo-medium.md
> +You see an excerpt of a specification document written in Markdown. More precisely you see a requirement with a title, a requirement ID and a description.
MarkDown

2018-05-22 15:51 UTC, kaklakariada commented on oft-live-demo-medium.md
> +Incidentally I picked a the requirement that defines a "Specification Item".
I picked a the -> I picked the

2018-05-22 15:51 UTC, kaklakariada commented on oft-live-demo-medium.md
> +Next we are going to run a trace that focuses on this question only. We do this by filtering out all artifact types but `feat`, `req` and `dsn`. The first two are from the system requirements you nee
last -> last one

2018-05-22 15:51 UTC, kaklakariada commented on oft-live-demo-medium.md
> +As you can see at least from the perspective of the design document. While this doesn't mean the whole projects trace is green it at least proves that you did your job.
Not a complete sentence

2018-05-22 15:51 UTC, kaklakariada commented on oft-live-demo-medium.md
> +One of the reasons OFT features a plain text report and has a command line interface is that this combination is ideal for chaining OFT with other populare command line tools like `grep`.
populare -> popular

2018-05-22 15:51 UTC, kaklakariada commented on oft-live-demo-medium.md
> +Let's take this one step further an filter out a
filter out a ...?

2018-05-22 15:51 UTC, kaklakariada commented on oft-live-demo-medium.md
> +id='req~tracing.deep-coverage~1' && oft trace -v ALL doc src/main/java src/test/java | grep -Pzo 'ok.*'"$id"'.*\n([|].*\n)+'
`&&` is not required here

2018-05-22 15:51 UTC, kaklakariada commented on oft-live-demo-medium.md
> +* Text editor (e.g. vi)
Add entry: `xmllint`

2018-05-22 15:51 UTC, kaklakariada commented on oft-live-demo-medium.md
> +* OFT native (in / out)
Mention MarkDown format

2018-05-22 17:36 UTC, redcatbear commented on oft-live-demo-medium.md
> +sudo apt install openjdk-8-jre vim libxml2-utils
Fixed.

2018-05-22 17:36 UTC, redcatbear commented on oft-live-demo-medium.md
> +Set the necessary environment variables first. They are also needed in case you return later to a already set-up demonstration.
Fixed

2018-05-22 17:36 UTC, redcatbear commented on oft-live-demo-medium.md
> +demodir="$HOME/tmp/$project-demo-medium"
Because I plan a compact demo (20 min) too.

2018-05-22 17:36 UTC, redcatbear commented on oft-live-demo-medium.md
> +The following command produces a list of all requirement ID from OFT's feature list.
Fixed.

2018-05-22 17:37 UTC, redcatbear commented on oft-live-demo-medium.md
> +One of the reasons OFT features a plain text report and has a command line interface is that this combination is ideal for chaining OFT with other populare command line tools like `grep`.
Fixed.

2018-05-22 17:38 UTC, redcatbear commented on oft-live-demo-medium.md
> +Let's take this one step further an filter out a
Added missing parts.

2018-05-22 17:40 UTC, redcatbear commented on oft-live-demo-medium.md
> +id='req~tracing.deep-coverage~1' && oft trace -v ALL doc src/main/java src/test/java | grep -Pzo 'ok.*'"$id"'.*\n([|].*\n)+'
Right. Fixed.

2018-05-22 17:43 UTC, redcatbear commented on oft-live-demo-medium.md
> +* Text editor (e.g. vi)
Added.

2018-05-22 17:43 UTC, redcatbear commented on oft-live-demo-medium.md
> +* OFT native (in / out)
Done.

2018-05-24 18:55 UTC, kaklakariada approved these changes

2018-05-24 18:56 UTC, merged